services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mantén solo la contraseña de root
    ports:
      - "3307:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d  # Cargar scripts de inicialización
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: persona_db
      MONGO_INITDB_ROOT_PASSWORD: persona_db
      MONGO_INITDB_DATABASE: persona_db
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d  # Cargar scripts de inicialización
    networks:
      - my_network

  #rest-api:
   # build:
   #   context: .
   #   dockerfile: Dockerfile
   # container_name: rest-api-container
  #  environment:
  #    SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/persona_db  # Cambia a 'persona_db'
   #   SPRING_DATASOURCE_USERNAME: persona_db  # Cambiado de 'my_user' a 'persona_db'
    #  SPRING_DATASOURCE_PASSWORD: persona_db  # Cambiado de 'my_password' a 'persona_db'
     # SPRING_DATA_MONGODB_URI: mongodb://persona_db:persona_db@mongodb:27017/persona_db  # Cambia las credenciales de MongoDB
  #  ports:
  #    - "3000:3000"  # Mapea el puerto 3000 de la API al host
   # depends_on:
  #    - mariadb
   #   - mongodb
   # networks:
   #   - my_network

networks:
  my_network:
    driver: bridge

